### PR TITLE
Add matrix of policies and API level

### LINKED ISSUE #365: Policies Matrix with Android API and type
Create a Policies matrix with this information:

```
# Admin policies
- Password enabled
- Password quality
- Password minimum length
- Password minimum lower case
- Password minimum upper case
- Password minimum non letter
- Password minimum letters
- Password minimum numeric
- Password minimum symbols
- Maximum failed passwords for wipe
- Maximum time to lock
- Storage encryption
- Disable camera
- Deploy app
- Remove app
- Deploy file
- Remove file
- Use TLS
- Disable speakerphone
- Disable bluetooth
- Disable wifi
- Disable mobile line

# System policies
- Disable NFC (system)
- Disable Usb Mtp (system)
- Disable Usb Ptp (system)
- Disable Usb Adb (system)
- Disable create VPN Profiles
- Disable airplane mode (system)
- Disable GPS (system)
- Disable Hostpot/Tethering (system)
- Disable roaming (system)
- Disable screen capture
- Disable statusbar
```

And the minimum Android API require

### PR DESCRIPTION
**Pull request by Naylin15**
### Changes description
Add information with the compatibility between policies and api level

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [x] Docs have been added/updated

### References

Closes #365

### CODE REVIEW

**Comment by ajsb85** [comment]
Hi, @Naylin15 
A lot of warning and errors in the project site.
Could you fill a new issue related to this output in the CI?
Thanks

**Comment by Naylin15** [comment]
Hi @ajsb85 

I filled the issue about the CI outputs, #376

**Comment by ajsb85** [comment]
Hi, @rafaelje 
Please, provide a feedback about the contribution of Naylin.
http://flyve.org/android-mdm-agent/howtos/policies
These changes are ok for you?

**Comment by rafaelje** [comment]
The information is good for me if we can add a zebra background on the table will be fine 👍

**Pull request merged**
